export const CHANGE_TASK_UNCOMPLETE_REQUEST = "@change-task-complete/CHANGE_TASK_UNCOMPLETE_REQUEST"
export const CHANGE_TASK_UNCOMPLETE_SUCCESS = "@change-task-complete/CHANGE_TASK_UNCOMPLETE_SUCCESS"
export const CHANGE_TASK_UNCOMPLETE_FAILED = "@change-task-complete/CHANGE_TASK_UNCOMPLETE_FAILED"


